"""create users table

Revision ID: 77f79fb1fae0
Revises: 
Create Date: 2026-01-25 15:56:40.565594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f79fb1fae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Engineer', 'Staff', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.String(length=25), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=False, foreign_key=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
