"""create users table

Revision ID: 105c96512656
Revises: 
Create Date: 2026-01-26 01:51:49.447597

"""
from alembic import op
import sqlalchemy as sa

from app.models.enum import SecurityQuestion


# revision identifiers, used by Alembic.
revision = '105c96512656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True, auto_increment=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Engineer', 'SalesPerson', name='user_role_enum'), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('security_question', sa.Enum(SecurityQuestion, name='user_security_question'), nullable=True),
    sa.Column('security_response', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('company')
    # ### end Alembic commands ###
