"""removing enum temporarily

Revision ID: 53231ee5af8b
Revises: ebb91b2fd796
Create Date: 2026-01-26 22:59:56.614944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53231ee5af8b'
down_revision = 'ebb91b2fd796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.VARCHAR(length=12), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=11), nullable=False))

    # ### end Alembic commands ###
