"""initial

Revision ID: 5e861d39f84f
Revises: 
Create Date: 2026-01-27 23:30:22.755776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e861d39f84f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salt_hex', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('company_reg_no', sa.String(length=10), nullable=False),
    sa.Column('security_question', sa.String(length=50), nullable=False),
    sa.Column('security_response', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_reg_no'], ['company.reg_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('company')
    # ### end Alembic commands ###
