"""including enums again

Revision ID: 7209dc9e4800
Revises: 53231ee5af8b
Create Date: 2026-01-26 23:28:03.287602

"""
from alembic import op
import sqlalchemy as sa

from app.models.enum import SecurityQuestion


# revision identifiers, used by Alembic.
revision = '7209dc9e4800'
down_revision = '53231ee5af8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('Admin', 'Engineer', 'SalesPerson', name='user_role_enum'), nullable=False))
        batch_op.add_column(sa.Column('security_question', sa.Enum(SecurityQuestion, name='user_security_question'), nullable=False))
        batch_op.alter_column('tel',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tel',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('security_question')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
