"""included selling price

Revision ID: 83dd6e472ecc
Revises: 74ae015ede2f
Create Date: 2026-03-09 16:54:49.379890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dd6e472ecc'
down_revision = '74ae015ede2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
