"""same migration

Revision ID: 999f9cbbe6e4
Revises: b414d6886a86
Create Date: 2026-02-08 15:18:47.628634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999f9cbbe6e4'
down_revision = 'b414d6886a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('time_period',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('time_period',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
