"""fixed company size

Revision ID: a6d1ac647882
Revises: 999f9cbbe6e4
Create Date: 2026-02-12 22:46:32.613104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d1ac647882'
down_revision = '999f9cbbe6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_company')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_company_reg_no'), ['company_reg_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_company_reg_no'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reg_no', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('threshold', sa.NUMERIC(precision=3, scale=1), nullable=True),
    sa.Column('time_period', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no')
    )
    # ### end Alembic commands ###
