"""changed time period from nuber to numeric

Revision ID: b414d6886a86
Revises: df3e485d60ff
Create Date: 2026-02-08 15:09:02.305362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414d6886a86'
down_revision = 'df3e485d60ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('time_period',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('time_period',
               existing_type=sa.Numeric(precision=2, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
