"""added threshold

Revision ID: c0a6a8918359
Revises: 2ffae045abec
Create Date: 2026-02-08 00:55:25.580943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a6a8918359'
down_revision = '2ffae045abec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold', sa.Numeric(precision=3, scale=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('threshold')

    # ### end Alembic commands ###
