"""edited company table to include report time

Revision ID: df3e485d60ff
Revises: c0a6a8918359
Create Date: 2026-02-08 14:57:43.262806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3e485d60ff'
down_revision = 'c0a6a8918359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('time_period')

    # ### end Alembic commands ###
