"""update models

Revision ID: ebb91b2fd796
Revises: 105c96512656
Create Date: 2026-01-26 22:07:12.114286

"""
from alembic import op
import sqlalchemy as sa

from app.models.enum import SecurityQuestion


# revision identifiers, used by Alembic.
revision = 'ebb91b2fd796'
down_revision = '105c96512656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=35), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=35), nullable=False))
        batch_op.add_column(sa.Column('salt_hex', sa.String(length=64), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('security_question',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum(SecurityQuestion, name='user_security_question'),
               nullable=False)
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('security_question',
               existing_type=sa.Enum(SecurityQuestion, name='user_security_question'),
               type_=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.drop_column('salt_hex')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
