"""sync schema

Revision ID: f776fc9a03ce
Revises: 7209dc9e4800
Create Date: 2026-01-26 23:59:15.158546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f776fc9a03ce'
down_revision = '7209dc9e4800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length='20'),
               existing_nullable=False)
        batch_op.alter_column('security_question',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('security_question',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length='20'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
